### ISSUE TITLE
LilyGo T-Display S3

### ISSUE THREAD

**Issue by OriginalNode** [BruceDevices/firmware#672]
Will you support this device ?

**Comment by epiHATR** [comment]
now supported

**Comment by bmorcelli** [comment]
We just need to find a way to make navigation with only two btns..

Short Right press> Next
Long right press >Select
Short left press>prev
Long left press>Esc

It would be nice.. and for the keyboard, think of a logic to use it too

(Can keep the 3rd btn logic, but if it can work with only 2, better..)

**Comment by Grzybekrk** [comment]
Is working on amoled???

**Comment by djaysan** [comment]
@bmorcelli that's awesome ! 
t-display s3 here, i understand that we need to short pin 16 & ground to select an option. 
How de we wire an sd card reader? 
 
I did that on t-display 1.14 following [this guide](https://github.com/ATOMNFT/Marauder-T-display-TTGO?tab=readme-ov-file#esp32-marauder-info) but i suppose Bruce is different and the pin numbers as well

**Comment by bmorcelli** [comment]
I believe we need to make the SD, CC1101 and NRF pins configurable by software.. it would be easier to setup

Like having a field on bruce.conf, like 
'SD_pins: {SCK,Mosi,Miso,CS},
CC_pins: {SCK,Mosi,Miso,CS},
NRF_pins: {SCK,Mosi,Miso,CS}'

**Comment by epiHATR** [comment]
I tried but won't make it working, since the t-display-s3 is using parallel 8 bit so I got the error while compiling it

I use the same SCK, MISO, MOSI for NRF24 and CC1101, use different CE, CSN for NRF and CC1101, but it was unable to compile.

It looks like when we set TFT_PARALLEL_8_BIT for TFT_eSPI of lilygo t-display-s3, this line does not work.

```cplusplus
class "TFT_eSPI" has no member "getSPIinstance"C/C++(135)

```

**Comment by bmorcelli** [comment]
If it is using 8bit parallel, it shouldn't have the TFT_MOSI defined in the .ini or pinouts file..

Comment them out and it should work just fine

**Comment by epiHATR** [comment]
Thank you so much @bmorcelli , i'll try

**Comment by IncursioHack** [comment]
@epiHATR  Could you please provide us with feedback if the situation has been corrected?

**Comment by fehnapp** [comment]
I still dont understand how to get nrf 24 working on the t display s3 non touch, i tried the wiring posted up but uts not working? I went into the code on the bruce repo to and tried the wiring in there just to double check but it still didint work, how do i get it working?

**Comment by fehnapp** [comment]
Could anyone walk me through it
