### ISSUE TITLE
ESP32 2432S032R support

### ISSUE THREAD

**Issue by pipeninja** [BruceDevices/firmware#858]
Any chance support for this board might be added in the future?

https://www.tinytronics.nl/en/development-boards/microcontroller-boards/with-wi-fi/jingcai-esp32-2432s032r-i-3.2-inch-tft-lcd-display-320*240-pixels-with-resistive-touchscreen-esp32

It uses ST7789 display and XPT2406 for touch.

It'd be a great board because it already has a LIPO circuit on it and it's a good size.

There's a couple of really nice cases available as well on Thangs for 3D printing.

**Comment by pipeninja** [comment]
Specs and pinouts for this board can be found here:

http://www.lcdwiki.com/3.2inch_ESP32-32E_Display

**Comment by pipeninja** [comment]
I have one of these boards, as well as two of the capacitive display version (GT911 touch, I know, I know).

Willing to help with testing in anyway I can.

**Comment by bmorcelli** [comment]
Hey dude, I have added these boards to Launcher CYD-2432S032C and CYD-2432S032R

![Screenshot_20250302-170613.png](https://github.com/user-attachments/assets/10e9017d-2c35-4a67-a51b-fa1f536819fb)

Can you test it for me? They are on Beta Release yet.

https://bmorcelli.github.io/M5Stick-Launcher/

**Comment by pipeninja** [comment]
I saw  that, but they are 404'ing and I can't find the BIN files.

**Comment by pipeninja** [comment]
The beta versions flash, but they boot to a black screen. On both the R and the C.

**Comment by bmorcelli** [comment]
Ok, can you try again??

I believe I've fixed both boards on BetaRelease > CYD > CYD-2432S032R and C

it is not a final release, so I need your feedback to make a release over it

**Comment by pipeninja** [comment]
Capacative 3.2" still blank. Absolutely nothing. Flashing Resistive now.

Also you have the flash button CSS set to "hidden", I had to edit the HTML to get the button back!

**Comment by pipeninja** [comment]
Resistive display works!

**Comment by pipeninja** [comment]
The launcher loads, but the touch coordinates appear to be messed up...I can move to the next item, but not previous and I can't hit select. Next appears to be in the middle of the screen.

I think the touch is upside down.

**Comment by pipeninja** [comment]
Yeah touch is wonky in all orientations. It's like it's off by 90 degrees or something.

**Comment by pipeninja** [comment]
The UI itself though displays perfectly!

**Comment by bmorcelli** [comment]
I believe I fixed the Resistive orientation now,

And maybe the Capacitive can be working too.. but I need the Serial Monitor Logs

The flasher issue was fixed too..

**Comment by pipeninja** [comment]
Flashed the new resistive firmware. Still an issue with the touch...it is rotated 90 degrees. By default it boots into landscape layout with the USB port to the left and LED to the right. The left edge along the USB side is where the "touch" areas are. If the screen was portrait with the USB at the bottom, the touch orientation would be correct.

The touch needs to rotate 90 degrees counter clockwise.

Not sure how to dump serial logs, the tool built into the webflasher outputs an empty text file.

What I see in the console when I boot up is this:

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1276
ho 0 tail 12 room 4
load:0x40078000,len:13232
load:0x40080400,len:3076
entry 0x400805f0
[boot] Turned on because (1= POWERON_RESET) (Other= Probably forced by launcher)--> 1
E (518) esp_core_dump_flash: N��ɕ�dump partition found!
E (518) esp_core_dump_flash: No core dump partition found!
E (312) ledc: ledc_set_duty(725): LEDC is not initialized
E (313) ledc: ledc_update_duty(653): LEDC is not initialized
Touch IC Started
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!
Press the button to enter the Launcher!

**Comment by mickadotembed** [comment]
bonjour le cyd 2432s032C fonctionne bien sauf pour le changement d orientation plus rien ne va avec le tactile

**Comment by michaelolesen77-eng** [comment]
I have a 3.2" and a 4" of the cyd and those 2 are not supported i have tried them all the some of them work but not the touch feature :( Does anyone have a fix ?

**Comment by francescomcrtl** [comment]
im waiting asw
